# image: https://hub.docker.com/_/memcached
# panel image: https://hub.docker.com/r/hatamiarash7/memcached-admin

version: '3.8'
services:
  memcached:
    image: memcached:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
     - '${APP_DB_PORT}:11211'
    env_file: .env
    command:
     - '-m ${APP_MEMORY}'
     - '-c ${APP_MEMORY}'

  memadmin:
    image: hatamiarash7/memcached-admin:master
    container_name: $APP_NAME-panel
    restart: unless-stopped
    ports:
     - '$APP_PANEL_PORT:80'
    environment: 
     - 'MEMCACHED_HOST=memcached'

networks:
  default:
    name: ${APP_NETWORK}
    external: true
