# CMAK is a tool for managing Apache Kafka clusters
# repository: https://github.com/yahoo/CMAK
# image: https://hub.docker.com/r/hlebalbau/kafka-manager
# default user: admin, password:123456

version: '3.8'

services:
  kafka_manager:
    build: .
    image: cmak
    container_name: "${APP_NAME}"
    restart: unless-stopped
    env_file: .env
    ports:
      - "${APP_HTTP_PORT}:9000"
    environment:
      KAFKA_MANAGER_USERNAME: ${APP_USER}
      KAFKA_MANAGER_PASSWORD: ${APP_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true
