version: '3.8'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:centos-5.4-${APP_VERSION}
  container_name: ${APP_CONTAINER_NAME}-server
  restart: always
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ${VOLUMES_PATH_PREFIX}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ${VOLUMES_PATH_PREFIX}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
  volumes_from:
   - zabbix-snmptraps:ro
  links:
   - mysql-server:mysql-server
   - zabbix-java-gateway:zabbix-java-gateway
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      memory: 1G
    reservations:
      memory: 512M
  env_file:
   - .env_srv
  environment:
   - DB_SERVER_HOST=${APP_DB_MYSQL_HOST}
   - DB_SERVER_PORT=${APP_DB_MYSQL_PORT}
   - MYSQL_ROOT_PASSWORD=${APP_DB_MYSQL_PASSWORD}
   - MYSQL_PASSWORD=${APP_DB_MYSQL_PASSWORD}
   - MYSQL_DATABASE=${APP_DB_MYSQL_NAME}
  depends_on:
   - mysql-server
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "centos"

 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:centos-5.4-${APP_VERSION}
  container_name: ${APP_CONTAINER_NAME}-web
  restart: always
  ports:
   - "${APP_PORT}:8080"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ${VOLUMES_PATH_PREFIX}/etc/ssl/apache2:/etc/ssl/apache2:ro
   - ${VOLUMES_PATH_PREFIX}/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  deploy:
   resources:
    limits:
      memory: 512M
    reservations:
      memory: 256M
  environment:
   - DB_SERVER_HOST=${APP_DB_MYSQL_HOST}
   - DB_SERVER_PORT=${APP_DB_MYSQL_PORT}
   - MYSQL_ROOT_PASSWORD=${APP_DB_MYSQL_PASSWORD}
   - MYSQL_PASSWORD=${APP_DB_MYSQL_PASSWORD}
  env_file:
   - .env_web
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "centos"

 zabbix-agent:
  image: zabbix/zabbix-agent:centos-5.4-${APP_VERSION}
  container_name: ${APP_CONTAINER_NAME}-agent
  restart: always
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ${VOLUMES_PATH_PREFIX}/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  deploy:
   resources:
    limits:
      memory: 128M
    reservations:
      memory: 64M
   mode: global
  env_file:
   - .env_agent
  privileged: true
  pid: "host"
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "centos"

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:centos-5.4-${APP_VERSION}
  container_name: ${APP_CONTAINER_NAME}-java
  restart: always
  ports:
   - "10052:10052"
  deploy:
   resources:
    limits:
      memory: 512M
    reservations:
      memory: 256M
  env_file:
   - .env_java
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "centos"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:centos-5.4-${APP_VERSION}
  container_name: ${APP_CONTAINER_NAME}-snmptraps
  restart: always
  ports:
   - "162:1162/udp"
  volumes:
   - ${VOLUMES_PATH_PREFIX}/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
  deploy:
   resources:
    limits:
      memory: 256M
    reservations:
      memory: 128M
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "centos"

 mysql-server:
  image: mysql:${APP_DB_MYSQL_VERSION}
  container_name: ${APP_CONTAINER_NAME}-mysql
  restart: always
  ports: 
   - ${APP_DB_MYSQL_PORT}:3306
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - ${VOLUMES_PATH_PREFIX}/var/lib/mysql:/var/lib/mysql:rw
  environment: 
   - DB_SERVER_HOST=${APP_DB_MYSQL_HOST}
   - MYSQL_ROOT_PASSWORD=${APP_DB_MYSQL_PASSWORD}
   - DB_SERVER_PORT=${APP_DB_MYSQL_PORT}
   - MYSQL_USER=${APP_DB_MYSQL_USER}
   - MYSQL_PASSWORD=${APP_DB_MYSQL_PASSWORD}
  security_opt:
   - seccomp:unconfined
  stop_grace_period: 1m

 db_data_mysql:
  image: busybox
  container_name: ${APP_CONTAINER_NAME}-data
  volumes:
   - ${VOLUMES_PATH_PREFIX}/var/lib/mysql:/var/lib/mysql:rw

networks:
  default:
    name: ${APP_NETWORK}
