# image: https://github.com/huginn/huginn/pkgs/container/huginn
# docs1: https://github.com/huginn/huginn/blob/master/doc/docker/install.md
# docs2: https://hub.docker.com/r/huginn/huginn


version: '3.8'

services:
  huginn:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '$APP_HTTP_PORT:3000'
    volumes:
      - 'huginn-mysql:/var/lib/mysql'

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  huginn-mysql:
