# kafka image: https://hub.docker.com/r/bitnami/kafka
# cmak: https://github.com/eshepelyuk/cmak-docker

version: "3.8"

services:
  kafka:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - "$APP_DB_KAFKA_PORT:9092"
    volumes:
      - "kafka_data:/bitnami"
    env_file: .env
    depends_on:
      - zookeeper

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: $APP_NAME-zookeeper
    restart: unless-stopped
    ports:
      - "$APP_ZOOMKEEPER_PORT:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    env_file: .env

  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    container_name: $APP_NAME-cmak
    restart: unless-stopped
    ports:
      - "$APP_CMAK_PORT:9000"
    env_file: .env
    environment:
      KAFKA_MANAGER_USERNAME: $APP_USER
      KAFKA_MANAGER_PASSWORD: $APP_PASSWORD

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  default:
    name: ${APP_NETWORK}
    external: true
