# image: https://hub.docker.com/r/chat2db/chat2db
# docs: https://github.com/chat2db/Chat2DB#-docker-installation


version: '3.8'

services:
  chat2db:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '$APP_HTTP_PORT:10824'
    volumes:
      - 'chat2db:/root/.chat2db'

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  chat2db:
