# image and compose: https://hub.docker.com/r/martinhelmich/typo3

version: '3.8'

services:
  typo3:
    image: martinhelmich/typo3:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - typo3fileadmin:/var/www/html/fileadmin
      - typo3conf:/var/www/html/typo3conf
      - typo3uploads:/var/www/html/uploads
      - typo3temp:/var/www/html/typo3temp
    restart: unless-stopped
    environment:
      TYPO3_DB_USER: ${APP_DB_MYSQL_USER}
      TYPO3_DB_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      TYPO3_DB_HOST: mysql
    command: bash -c "cat /my_cmd > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    configs:
      - source: my_cmd
      
  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  typo3fileadmin:
  typo3conf:
  typo3uploads:
  typo3temp:
  mysql:

configs:
  my_cmd:
    file: ./cmd.sh
