# docs: https://github.com/google/cadvisor.git
# image: https://hub.docker.com/r/google/cadvisor

version: "3.8"

services:
  cadvisor:
    image: "google/cadvisor:${APP_VERSION}"
    restart: always
    ports:
      - "${APP_HTTP_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys/:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  default:
    name: ${APP_NETWORK}
    external: true
