# image: https://hub.docker.com/r/mautic/mautic/tags
# docs: https://github.com/mautic/docker-mautic


version: '3.8'

services:
  mautic:
    image: mautic/mautic:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - mautic:/var/www/html
    env_file:
      - .env
    environment:
      # MAUTIC_DB_USER must root, otherwise container error
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${APP_DB_MYSQL_NAME}
    depends_on:
      - mysql
    restart: unless-stopped


  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mautic:
  mysql: