# image: https://hub.docker.com/r/easysoft/zentao
# docs: https://github.com/easysoft/zentaopms

version: '3.8'

services:
  zentao:
    image: easysoft/zentao:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - zentao:/data
    env_file: .env
    environment:
      # The belows vars is need, otherwise container error
      ZT_MYSQL_HOST: ${APP_NAME}-db
      ZT_MYSQL_PORT: 3306
      ZT_MYSQL_USER: ${APP_DB_MYSQL_USER}
      ZT_MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      ZT_MYSQL_DB: ${APP_DB_MYSQL_NAME}
    restart: unless-stopped
      
  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  zentao:
  mysql_data:

configs:
  my_cmd:
    file: ./cmd.sh
