version: "3.8"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server:$APP_VERSION
    container_name: $APP_NAME
    env_file: .env
    environment:
      - PASSWORD=$APP_PASSWORD
      - SUDO_PASSWORD=$APP_PASSWORD
      - PROXY_DOMAIN=$APP_URL
    volumes:
      - "code:/config"
    ports:
      - $APP_HTTP_PORT:8443
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  code:
