# image: https://hub.docker.com/r/appsmith/appsmith-ce
# docs: https://docs.appsmith.com/getting-started/setup/installation-guides/docker/


version: '3.8'

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - "$APP_HTTP_PORT:80"
    volumes:
      - appsmith:/appsmith-stacks
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  appsmith:
