# mongo only for test

version: "3.8"
services:
  mongo-express:
    image: mongo-express:${APP_VERSION}
    restart: unless-stopped
    container_name: ${APP_NAME}
    ports:
      - "${APP_HTTP_PORT}:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAMEL=${APP_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${APP_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    profiles:
      - db

networks:
  default:
    name: ${APP_NETWORK}
    external: true
