# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm


version: '3.8'

services:
  redpanda-console:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  suitecrm: