# The default username is guacadmin with password guacadmin.

version: '3.8'

services:
  guacd:
    container_name: ${APP_CONTAINER_NAME}-guacd
    image: guacamole/guacd
    restart: unless-stopped
    depends_on:
      - guacamole-preparation
    volumes:
      - drive:/drive:rw
      - record:/record:rw
      
  guacamole-preparation:
    image: guacamole/guacamole:${APP_VERSION}
    entrypoint: [ "bash", "-c", "chmod -R +x /opt/guacamole/init && /opt/guacamole/bin/initdb.sh --postgres > /opt/guacamole/init/initdb.sql"]
    user: root
    privileged: true
    volumes:
      - ./init:/opt/guacamole/init
    restart: on-failure
    
  postgres:
    image: postgres:${APP_DB_POSTGRESQL_VERSION}
    restart: unless-stopped
    container_name: ${APP_CONTAINER_NAME}-postgres
    depends_on:
      - guacamole-preparation
    environment:
      - PGDATA=/var/lib/postgresql/data/guacamole
      - POSTGRES_DB=${APP_DB_POSTGRESQL_NAME}
      - POSTGRES_PASSWORD=${APP_DB_POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${APP_DB_POSTGRESQL_USER}
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
      
  guacamole:
    image: guacamole/guacamole:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
     - guacd
     - postgres
     - guacamole-preparation
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_DATABASE=${APP_DB_POSTGRESQL_NAME}
      - POSTGRES_HOSTNAME=${APP_DB_POSTGRESQL_HOST}
      - POSTGRES_PASSWORD=${APP_DB_POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${APP_DB_POSTGRESQL_USER}
    ports:
      - ${APP_HTTP_PORT}:8080
    
volumes:
  postgres:
  record:
  drive:
  
networks:
  default:
    name: ${APP_NETWORK}
    external: true
