# image: https://hub.docker.com/_/xwiki
# docs: https://github.com/xwiki/xwiki-docker/blob/master/README.md

version: '3.8'

services:
  xwiki:
    image: xwiki:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - $APP_HTTP_PORT:8080
    volumes:
      - xwiki:/usr/local/xwiki
    env_file:
      - .env
    environment:
      - DB_USER=${APP_DB_MYSQL_USER}
      - DB_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - DB_HOST=mysql
    links: 
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: $APP_NAME-mysql
    restart: unless-stopped
    ports:
     - $APP_DB_MYSQL_PORT:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $APP_DB_MYSQL_NAME
      MYSQL_USER: $APP_DB_MYSQL_USER
      MYSQL_PASSWORD: $APP_DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $APP_DB_MYSQL_PASSWORD

networks:
  default:
    name: $APP_NETWORK
    external: true

volumes:
  xwiki:
  mysql: