# image compose and docs: https://hub.docker.com/_/nextcloud

version: '3.8'

services:
  nextcloud:
    image: nextcloud:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - nextcloud:/var/www/html
      - nextcloud-data:/var/www/html/data
    env_file: .env
    environment:
      - MYSQL_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${APP_DB_MYSQL_NAME}
      - MYSQL_USER=${APP_DB_MYSQL_USER}
      - MYSQL_HOST=${APP_NAME}-db
    links:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

volumes:
  nextcloud:
  nextcloud-data:
  mysql:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
