# image: https://gallery.ecr.aws/gravitational/teleport
# docs: https://goteleport.com/docs/management/guides/docker/
# docs: https://goteleport.com/docs/try-out-teleport/docker-compose/


version: '3.8'

services:
  teleport-configure:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME-configure
    entrypoint: /bin/sh
    hostname: localhost
    command: -c "if [ ! -f /etc/teleport/teleport.yaml ]; then teleport configure > /etc/teleport/teleport.yaml; fi"
    volumes:
      - ./src/config:/etc/teleport

  teleport:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    entrypoint: /bin/sh
    hostname: localhost
    command: -c "sleep 1 && /usr/bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3025:3025"
      - '${APP_HTTP_PORT}:3080'
    volumes:
      - ./src/config:/etc/teleport
      - teleport_data:/var/lib/teleport
    depends_on:
      - teleport-configure

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  teleport_config:
  teleport_data:
