# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm


version: '3.8'

services:
  kasmweb:
    image: kasmweb/$APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    shm_size: '512m'
    env_file:
      - .env
    ports:
      - '$APP_HTTP_PORT:6901'

networks:
  default:
    name: $APP_NETWORK
    external: true
