# image: https://hub.docker.com/r/gitlab/gitlab-ce
# docs: https://gitlab.com/gitlab-org/omnibus-gitlab/tree/master/docker
# postgresql is in this container

version: '3.8'

services:

  gitlab:
    image: $APP_IMAGEURL:$APP_VERSION
    container_name: "$APP_NAME"
    hostname: "$APP_URL"
    env_file: .env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url rule: the protocol must be http://, can not use https://
        # external_url 'http://$APP_URL'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        # Add any other gitlab.rb configuration here, each on its own line
        # other
    shm_size: '256m'
    restart: unless-stopped
    ports:
      - '${APP_HTTP_PORT}:80'
      - '23:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: $APP_NAME-runner
    restart: unless-stopped
    volumes:
      - gitlab_runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner:
