# image: https://hub.docker.com/r/awesometic/docusaurus

version: '3.8'

services:
  docusaurus:
    image: awesometic/docusaurus:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:80'
    env_file:
      - .env
    volumes:
      - 'docusaurus:/docusaurus'

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  docusaurus:
