# refer repository: https://github.com/deviantony/docker-elk
# image: https://hub.docker.com/_/elasticsearch
# docs: https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
# docs: https://www.elastic.co/guide/en/logstash/current/docker-config.html

version: '3.8'

services:

  kibana:
    image: kibana:${APP_VERSION}
    container_name: ${APP_NAME}-kibana
    restart: unless-stopped
    volumes:
      - ./src/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: '["http://$APP_NAME-elasticsearch:9200"]'
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rlc3Q6bU5CMTVuNEZTdG1BaHBvSWFjVXlHZw
      SERVER_HOST: "0.0.0.0"
      SERVER_NAME: "kibana"
    ports:
      - ${APP_HTTP_PORT}:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:${APP_VERSION}
    container_name: ${APP_NAME}-elasticsearch
    restart: unless-stopped
    volumes:
      - ./src/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./src/elasticsearch/config/service_tokens:/usr/share/elasticsearch/config/service_tokens
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - ${APP_DB_ES_HTTP_PORT}:9200
      - ${APP_DB_ES_TCP_PORT}:9300
    env_file: .env
    environment:
      ELASTIC_USERNAME: ${APP_USER}
      ELASTIC_PASSWORD: ${APP_PASSWORD}

  logstash:
    image: logstash:${APP_VERSION}
    container_name: ${APP_NAME}-logstash
    restart: unless-stopped
    volumes:
      - ./src/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./src/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - ${APP_LOGSTASH_API_PORT}:9600
      - ${APP_LOGSTASH_TCP_PORT}:5000/tcp
      - ${APP_LOGSTASH_UDP_PORT}:5000/udp
      - ${APP_LOGSTASH_BEATS_PORT}:5044
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    user: root
    depends_on:
      - elasticsearch

  agent:
    image: elastic/elastic-agent-complete:${APP_VERSION}
    container_name: ${APP_NAME}-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://${APP_NAME}-elasticsearch
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL3Rlc3Q6bU5CMTVuNEZTdG1BaHBvSWFjVXlHZw
    user: root
    depends_on:
      - elasticsearch

volumes:
  logstash:
  kibana:
  elasticsearch:
  agent:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
