# docs: https://doc.owncloud.com/server/10.8/admin_manual/installation/docker/
# image: https://hub.docker.com/r/owncloud/server

version: '3.8'

services:
  owncloud:
    image: owncloud/server:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:8080
    volumes:
      - owncloud:/mnt/data
    environment:
      - OWNCLOUD_DOMAIN=${APP_URL}
      - OWNCLOUD_TRUSTED_DOMAINS=${APP_URL}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=${APP_DB_MYSQL_NAME}
      - OWNCLOUD_DB_USERNAME=${APP_DB_MYSQL_USER}
      - OWNCLOUD_DB_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - OWNCLOUD_DB_HOST=${APP_NAME}-db
      - OWNCLOUD_ADMIN_USERNAME=${APP_USER}
      - OWNCLOUD_ADMIN_PASSWORD=${APP_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    env_file: .env
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on: 
      - mysql
      - redis
    restart: unless-stopped
    stdin_open: true
    tty: true

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

  redis:
    image: redis:6
    container_name: ${APP_NAME}-redis
    restart: unless-stopped
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

volumes:
  owncloud:
  redis:
  mysql:
 
networks:
  default:
    name: ${APP_NETWORK}
    external: true
