# image: https://hub.docker.com/r/bitnami/drupal

version: '3.8'

services:
  drupal:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - $APP_HTTP_PORT:8080
    volumes:
      - drupal:/bitnami/drupal
    restart: unless-stopped
    env_file: .env
    environment:
      - DRUPAL_DATABASE_HOST=$APP_NAME-db
      - DRUPAL_DATABASE_USER=$APP_DB_MYSQL_USER
      - DRUPAL_DATABASE_PASSWORD=$APP_DB_MYSQL_PASSWORD
      - DRUPAL_DATABASE_NAME=$APP_DB_MYSQL_NAME
      - DRUPAL_USERNAME=$APP_USER
      - DRUPAL_PASSWORD=$APP_PASSWORD
    depends_on:
      - db

  db:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: $APP_NAME-db
    restart: unless-stopped
    ports:
     - $APP_DB_MYSQL_PORT:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $APP_DB_MYSQL_NAME
      MYSQL_USER: $APP_DB_MYSQL_USER
      MYSQL_PASSWORD: $APP_DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $APP_DB_MYSQL_PASSWORD

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  drupal:
  mysql:
