# imag: https://hub.docker.com/r/pasharp/pal_server

version: '3.8'

services:
  palworld:
    image: $APP_REPO:$APP_VERSION
    restart: unless-stopped
    container_name: $APP_NAME
    ports:
      - $APP_UDP_PORT_SET:8211/udp
      - $APP_UDP2_PORT_SET:27015/udp
    environment:
        - PUID=1000
        - PGID=1000
        - PORT=8211 # Optional but recommended
        #- PLAYERS=16 # Optional but recommended
        #- SERVER_PASSWORD="worldofpals" # Optional but recommended
        - MULTITHREADING=true
        - RCON_ENABLED=true
        - RCON_PORT=25575
        - TZ=UTC
        #- ADMIN_PASSWORD="adminPasswordHere"
        - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
        - SERVER_NAME="World of Pals"
    volumes:
        - palworld_data:/palworld/
    env_file: .env

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  palworld_data: