# image: https://hub.docker.com/_/ghost

version: '3.8'

services:
  ghost:
    image: ghost:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - $APP_HTTP_PORT:2368
    env_file: .env
    environment:
      - database__connection__user=$APP_DB_MYSQL_USER
      - database__connection__password="$APP_DB_MYSQL_PASSWORD"
      - database__connection__database=$APP_DB_MYSQL_NAME
      # this url value is just an example, and is likely wrong for your environment!
      - url=http://$APP_URL
    volumes:
      - ghost:/var/lib/ghost
    depends_on:
      - db

  db:
    image: mysql:$APP_DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    ports:
     - $APP_DB_MYSQL_PORT:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $APP_DB_MYSQL_NAME
      MYSQL_USER: $APP_DB_MYSQL_USER
      MYSQL_PASSWORD: $APP_DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $APP_DB_MYSQL_PASSWORD

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  ghost:
  mysql:
