# image: https://hub.docker.com/r/linuxserver/mastodon
# docs: https://docs.linuxserver.io/images/docker-mastodon


version: '3.8'

services:
  mastodon:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - '$APP_HTTP_PORT:80'
    env_file: .env
    volumes:
      - 'mastodon_config:/config'
    restart: unless-stopped

  postgres:
    image: postgres:$APP_DB_POSTGRESQL_VERSION
    container_name: $APP_NAME-db
    environment:
      POSTGRES_DB: $APP_DB_POSTGRESQL_NAME
      POSTGRES_USER: $APP_DB_POSTGRESQL_USER
      POSTGRES_PASSWORD: $APP_DB_POSTGRESQL_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: redis:$APP_DB_REDIS_VERSION
    container_name: $APP_NAME-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

networks:
  default:
    name: $APP_NETWORK
    external: true

volumes:
  mastodon_config:
  postgres:
  redis: