# image: https://hub.docker.com/r/dgraph/dgraph/
# docs: https://dgraph.io/docs/get-started/#step-1-run-dgraph

version: '3.8'

services:
  zero:
    image: dgraph/dgraph:${DB_DGRAPH_VERSION}
    container_name: ${APP_NAME}-zero
    volumes:
      - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:${DB_DGRAPH_VERSION}
    container_name: ${APP_NAME}-alpha
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080

  ratel:
    image: dgraph/ratel:${DB_DGRAPH_VERSION}
    container_name: ${APP_NAME}-ratel
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  dgraph:
