# image: https://hub.docker.com/_/matomo
# docs: https://matomo.org/faq/on-premise/installing-matomo/


version: '3.8'

services:
  matomo:
    image: $APP_REPO:$APP_VERSION
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:80'
    env_file: .env
    environment:
      - MATOMO_DATABASE_HOST=${APP_NAME}-db
      - MATOMO_DATABASE_USERNAME=${APP_DB_MYSQL_USER}
      - MATOMO_DATABASE_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${APP_DB_MYSQL_NAME}
    volumes:
      - 'matomo:/var/www/html'
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  matomo:
