# imag: https://hub.docker.com/_/postgres

version: '3.8'
services:
  postgres:
    image: postgres:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
     - ${APP_DB_POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${APP_DB_POSTGRES_NAME}
      POSTGRES_USER: ${APP_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_DB_POSTGRES_PASSWORD}
    
volumes:
  postgres:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
