# image: base on Dockerhub php image

version: '3.8'

services:
  opencart:
    image: websoft9dev/opencart:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
     - ${APP_HTTP_PORT}:80
    volumes:
      - opencart:/var/www/html
      - ./src/php_exra.ini:/usr/local/etc/php/conf.d/php_exra.ini
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_HOST: ${APP_NAME}-db
    links: 
      - mysql
    command: bash -c "cat /my_cmd > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    configs:
      - source: my_cmd

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  opencart:
  mysql_data:

configs:
  my_cmd:
    file: ./cmd.sh
