# image and compose: https://hub.docker.com/r/pydio/cells
# more compose: https://github.com/pydio/cells/tree/main/tools/docker

version: '3.8'

services:
  pydio:
    image: pydio/cells:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - $APP_HTTP_PORT:8080
      - $APP_GRPC_PORT:33060
    volumes:
      - pydio:/var/cells
      - ./src/install-conf.yml:/pydio/config/install.yml:ro
    env_file:
      - .env
    restart: unless-stopped

  mysql:
    image: mysql:$APP_DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    ports:
     - $APP_DB_MYSQL_PORT:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $APP_DB_MYSQL_NAME
      MYSQL_USER: $APP_DB_MYSQL_USER
      MYSQL_PASSWORD: $APP_DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $APP_DB_MYSQL_PASSWORD

networks:
  default:
    name: $APP_NETWORK
    external: true

volumes:
  pydio:
    driver: local
  mysql:
    driver: local
