# docs: https://github.com/joomla-docker/docker-joomla
# image: https://hub.docker.com/r/websoft9dev/discuz

version: '3.8'

services:
  discuz:
    image: websoft9dev/discuz:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - '${APP_HTTP_PORT}:80'
    env_file: .env
    environment:
      - DISCUZ_DB_HOST=$APP_NAME-db
      - DISCUZ_DB_USER=$APP_DB_MYSQL_USER
      - DISCUZ_DB_DATABASE=$APP_DB_MYSQL_NAME
      - DISCUZ_DB_PASSWORD=$APP_DB_MYSQL_PASSWORD
    entrypoint:
      - bash
      - -c
      - cat /my_cmd > cmd.sh && chmod +x /var/www/html/cmd.sh && /var/www/html/cmd.sh
    volumes:
      - discuz:/var/www/html
      - ./src/php_exra.ini:/usr/local/etc/php/conf.d/php_exra.ini
    depends_on:
      - db
    configs:
      - source: my_cmd
      
  db:
    image: mysql:$APP_DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: $APP_DB_MYSQL_PASSWORD
      MYSQL_DATABASE: $APP_DB_MYSQL_NAME
      MYSQL_USER: $APP_DB_MYSQL_USER
      MYSQL_PASSWORD: $APP_DB_MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  discuz:

configs:
  my_cmd:
    file: ./cmd.sh
