# iamge: https://container-registry.oracle.com/

version: '3.8'

services:
  oracledb:
    image: container-registry.oracle.com/database/${APP_DB_ORACLE_EDITION}:${APP_DB_ORACLE_VERSION}
    container_name: ${APP_NAME}-db  
    environment:
      ORACLE_CHARACTERSET: ${DB_CHARACTERSET}
      ORACLE_PWD: ${APP_DB_ORACLE_PASSWORD}
      ORACLE_SID: ${APP_DB_ORACLE_SID}
      ORACLE_PDB: ${APP_DB_ORACLE_PDB}
      INIT_SGA_SIZE: ${APP_DB_ORACLE_SGA}
      INIT_PGA_SIZE: ${APP_DB_ORACLE_PGA}
      ENABLE_ARCHIVELOG: true
    volumes:
      - oracledb:/opt/oracle/oradata
    ports:
      -  ${APP_DB_ORACLE_PORT}:1521
      -  ${DB_MANAGE_PORT}:5500
    restart: unless-stopped

  apex:
    image: container-registry.oracle.com/database/ords:${APP_VERSION}
    container_name: ${APP_NAME} 
    depends_on:
      - oracledb
    env_file: .env
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo 'CONN_STRING=sys/$APP_DB_ORACLE_PASSWORD@oracledb:$APP_DB_ORACLE_PORT/${APP_DB_ORACLE_PDB}' > /opt/oracle/variables/conn_string.txt
        sed -i 's/Welcome_1/${APP_PASSWORD}/g' /opt/oracle/apex/setapexadmin.sql
        bash /entrypoint.sh
    ports:
      -  ${APP_HTTP_PORT}:8181
    restart: unless-stopped
    
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  oracledb:
