# image: https://hub.docker.com/r/tuxgasy/dolibarr
# docs: https://github.com/tuxgasy/docker-dolibarr

version: '3.8'

services:
    mariadb:
        image: mariadb:${APP_DB_MARIADB_VERSION}
        container_name: ${APP_NAME}-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${APP_DB_MARIADB_PASSWORD}
            MYSQL_DATABASE: ${APP_DB_MARIADB_NAME}
            MYSQL_USER: ${APP_DB_MARIADB_USER}
            MARIADB_PASSWORD: ${APP_DB_MARIADB_PASSWORD}
        volumes:
            - mariadb:/var/lib/mysql

    dolibarr:
        image: tuxgasy/dolibarr:${APP_VERSION}
        container_name: ${APP_NAME}
        restart: unless-stopped
        env_file: .env
        environment:
            DOLI_DB_HOST: ${APP_NAME}-db
            DOLI_DB_USER: ${APP_DB_MARIADB_USER}
            DOLI_DB_PASSWORD: ${APP_DB_MARIADB_PASSWORD}
            DOLI_DB_NAME: ${APP_DB_MARIADB_NAME}
            DOLI_ADMIN_LOGIN: ${APP_USER}
            DOLI_ADMIN_PASSWORD: ${APP_PASSWORD}
        ports:
            - "${APP_HTTP_PORT}:80"
        volumes:
            - dolibarr_html:/var/www/html
            - dolibarr_documents:/var/www/documents
        links:
            - mariadb
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mariadb:
  dolibarr_html:
  dolibarr_documents:
