version: '3.8'

services:
  proxy:
    image: jc21/nginx-proxy-manager:${APP_VERSION}
    restart: always
    container_name: nginxproxymanager
    ports:
      - '80:80'
      - '9001:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
 
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  nginx_data:
  nginx_letsencrypt:
