services:
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - mysql_data:/var/lib/mysql
     - mysql_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD

volumes:
  mysql_data:
  mysql_conf:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
