x-swift-defaults: &swift_defaults
  restart: always
  command: bash -c "cat /swift_service > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
  working_dir: /data/apps
  configs:
    - source: swift_service

services:

  swift5.6:
    container_name: swift5.6
    image: swift:5.6
    volumes: 
      - swift5.6:/data/apps
    <<: *swift_defaults

volumes:
  swift5.6:
  swift5.5:
  swift5.4:
  swift5.3:
  swift5.2:
  swift5.1:
  swift5.0:
  swift4.2:

configs:
  swift_service:
    file: ./config/swift/service.sh

networks:
  default:
    name: ${APP_NETWORK}
    external: true
