# docs: https://docs.alfresco.com/content-services/community/install/containers/docker-compose/
# source: https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml
# Modified by Websoft9: replace using variable, volume define and bind

version: "3.8"

services:
  alfresco:
    image: alfresco/alfresco-content-repository-community:$APP_VERSION-M2
    container_name: $APP_NAME
    restart: unless-stopped
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 1500M
    volumes:
      - alfresco:/usr/local/tomcat/alf_data
    environment:
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
        "
      JAVA_OPTS: "
        -Dalfresco_user_store.adminpassword=$APP_ENCRYPT_PASSWORD
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=$APP_DB_POSTGRESQL_PASSWORD
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.http.connection.timeout=1000
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=$APP_URL
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Ddeployment.method=DOCKER_COMPOSE
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        "

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.5.7
    container_name: $APP_NAME-transform
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1536M
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
    ports:
      - "8090:8090"

  share:
    image: alfresco/alfresco-share:$APP_VERSION-M2
    container_name: $APP_NAME-share
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: "
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=$APP_URL
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
        "

  postgres:
    image: postgres:$APP_DB_POSTGRESQL_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - POSTGRES_PASSWORD=$APP_DB_POSTGRESQL_PASSWORD
      - POSTGRES_USER=$APP_DB_POSTGRESQL_USER
      - POSTGRES_DB=$APP_DB_POSTGRESQL_NAME
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - $APP_DB_POSTGRESQL_PORT:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql

  solr6:
    image: alfresco/alfresco-search-services:2.0.3
    container_name: $APP_NAME-solr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      # Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      # Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      # Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS: "
          -Dalfresco.secureComms.secret=secret
      "
    ports:
      - "8083:8983" # Browser port

  activemq:
    image: alfresco/alfresco-activemq:$MQ_ACTIVEMQ_VERSION
    container_name: $APP_NAME-activemq
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "$MQ_ACTIVEMQ_PORT:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP

  proxy:
    image: alfresco/alfresco-acs-nginx:3.2.0
    container_name: $APP_NAME-proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      DISABLE_PROMETHEUS: "true"
      DISABLE_SYNCSERVICE: "true"
      DISABLE_ADW: "true"
    depends_on:
      - alfresco
    ports:
      - "$APP_HTTP_PORT:8080"
    links:
      - alfresco
      - share

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  postgres_data:
  postgres_logs:
  alfresco:
