# refer to: https://github.com/bitnami/bitnami-docker-moodle
# image: https://hub.docker.com/r/bitnami/moodle

version: "3.8"

services:
  moodle:
    image: docker.io/bitnami/moodle:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_DATABASE_HOST=${APP_NAME}-db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${APP_DB_MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MOODLE_DATABASE_NAME=${APP_DB_MARIADB_NAME}
      - MOODLE_USERNAME=${APP_USER}
      - MOODLE_PASSWORD=${APP_PASSWORD}
    ports:
      - "${APP_HTTP_PORT}:8080"
    env_file:
      - .env
    volumes:
      - "moodle_data:/bitnami/moodle"
      - "moodledata_data:/bitnami/moodledata"
    depends_on:
      - mariadb

  mariadb:
    image: docker.io/bitnami/mariadb:${APP_DB_MARIADB_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${APP_DB_MARIADB_USER}
      - MARIADB_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MARIADB_DATABASE=${APP_DB_MARIADB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - ${APP_DB_MARIADB_PORT}:3306
    volumes:
      - "mariadb_data:/bitnami/mariadb"

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
