# image: https://hub.docker.com/r/bitnami/magento

version: '3.8'

services:
  magento:
    image: docker.io/bitnami/magento:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - '$APP_HTTP_PORT:80'
    env_file:
      - .env
    environment:
      - MAGENTO_HOST=$APP_URL
      - MAGENTO_DATABASE_USER=$APP_DB_MARIADB_USER
      - MAGENTO_DATABASE_NAME=$APP_DB_MARIADB_NAME
      - MAGENTO_DATABASE_PASSWORD=$APP_DB_MARIADB_PASSWORD
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch

  magentocli:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID-cli
    volumes:
      - magento_data:/data
    depends_on:
      - magento
    entrypoint: |
      /bin/sh -c "
      apt update -y
      apt install -y --no-install-recommends wget
      while [ ! -f /data/bin/magento ]; do
        echo 'Waiting for bin/magento to be created...'
        sleep 10
      done
      # This url is download from https://raw.githubusercontent.com/magento-l10n/language-zh_CN/master/zh_CN.csv
      # When update magento, you should update src/zh_CN.csv file
      wget https://websoft9.github.io/docker-library/apps/magento/src/zh_CN.csv -O /data/vendor/magento/language-zh_hans_cn/zh_CN.csv
      cd /data
      bin/magento setup:static-content:deploy zh_Hans_CN
      bin/magento indexer:reindex
      bin/magento setup:store-config:set --base-url="http://$APP_URL/"
      bin/magento setup:store-config:set --base-url-secure="https://$APP_URL/"
      bin/magento cache:clean
      bin/magento cache:flush
      "
      
  mariadb:
    image: docker.io/bitnami/mariadb:$APP_DB_MARIADB_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    environment:
      - MARIADB_USER=$APP_DB_MARIADB_USER
      - MARIADB_DATABASE=$APP_DB_MARIADB_NAME
      - MARIADB_PASSWORD=$APP_DB_MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$APP_DB_MARIADB_PASSWORD
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    restart: unless-stopped
    container_name: $APP_NAME-elasticsearch
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  default:
    name: ${APP_NETWORK}
    external: true
