# image: https://hub.docker.com/r/bitnami/magento

version: '3.8'

services:
  magento:
    image: docker.io/bitnami/magento:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - '$APP_HTTP_PORT:80'
    env_file:
      - .env
    environment:
      - MAGENTO_HOST=$APP_URL
      - MAGENTO_DATABASE_USER=$APP_DB_MARIADB_USER
      - MAGENTO_DATABASE_NAME=$APP_DB_MARIADB_NAME
      - MAGENTO_DATABASE_PASSWORD=$APP_DB_MARIADB_PASSWORD
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch

  mariadb:
    image: docker.io/bitnami/mariadb:$APP_DB_MARIADB_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    environment:
      - MARIADB_USER=$APP_DB_MARIADB_USER
      - MARIADB_DATABASE=$APP_DB_MARIADB_NAME
      - MARIADB_PASSWORD=$APP_DB_MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$APP_DB_MARIADB_PASSWORD
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    restart: unless-stopped
    container_name: $APP_NAME-elasticsearch
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  default:
    name: ${APP_NETWORK}
    external: true
