# image: https://hub.docker.com/r/typesense/typesense/tags
# docs: https://typesense.org/docs/guide/install-typesense.html
# https://typesense.org/docs/guide/docsearch.html#add-docsearch-meta-tags-optional
# https://typesense.org/docs/0.23.0/api/server-configuration.html#using-command-line-arguments

version: "3.8"

services:
  typesense:
    image: typesense/typesense:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    environment:
      - TYPESENSE_API_KEY=${APP_KEY}
      - TYPESENSE_DATA_DIR=${APP_DATA_PATH}
      - TYPESENSE_ENABLE_CORS=true
    ports:
      - "${APP_HTTP_PORT}:8108"
    volumes:
      - typesense:/data

  docsearch-scraper:
    image: typesense/docsearch-scraper:latest
    container_name: ${APP_NAME}-scraper
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    environment:
      - TYPESENSE_API_KEY=${APP_KEY}
      - TYPESENSE_HOST=${APP_HOST}
      - TYPESENSE_PORT=${APP_HTTP_PORT}
      - TYPESENSE_PROTOCOL=${APP_PROTOCOL}
      - CONFIG={
          "index_name":"websoft9",
          "start_urls":["https://support.websoft9.com/"],
          "selectors":{
            "lvl0":{              
              "selector":"(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]",
              "type":"xpath",
              "global":true,
              "default_value":"Documentation"},
            "lvl1":"header h1",
            "lvl2":"article h2",
            "lvl3":"article h3",
            "lvl4":"article h4",
            "lvl5":"article h5,article td:first-child",
            "lvl6":"article h6",
            "text":"article p, article li, article td:last-child"},
          "strip_chars":" .,;:#",
          "custom_settings":{
            "separatorsToIndex":"_",
            "attributesForFaceting":["language","version","type","docusaurus_tag"],
            "attributesToRetrieve":["hierarchy","content","anchor","url","url_without_anchor","type"]},          
          "conversation_id":["833762294"],
          "nb_hits":46250}
    depends_on:
      - typesense

networks:
  default:
    name: ${APP_NETWORK}
    external: true


volumes:
  typesense:
