# image: https://hub.docker.com/r/tensorflow/tensorflow
# docs: https://github.com/tensorflow/tensorflow

version: '3.8'

services:
  tensorflow:
    image: tensorflow/tensorflow:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
      # tensorboard port is 6006, but you need to start it on container by yourself 
      - '${APP_HTTP_PORT}:8888'
      - '${APP_GUI_PORT}:6006'
    env_file: .env
    volumes:
      - tensorflow:/tf/notebooks

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  tensorflow:
