# image: https://hub.docker.com/r/redislabs/redisinsight
# image: https://hub.docker.com/_/redis

version: '3.8'

services:
  redis:
    image: redis:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports: 
      - ${APP_DB_PORT}:6379
    env_file: .env
    volumes:
      - ./src/redis.conf:/etc/redis.conf:ro
      - redis_data:/data
    entrypoint: ["redis-server", "/etc/redis.conf"] 

  redisinsight:
    image: redislabs/redisinsight:${APP_GUI_VERSION}
    container_name: ${APP_NAME}-gui
    restart: unless-stopped
    ports:
      - "${APP_GUI_PORT}:8001"

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  redis_data:
