# https://hub.docker.com/_/vault
# docs: https://www.vaultproject.io/

version: '3.8'

services:
  vault:
    image: vault:${APP_VERSION}
    container_name: ${APP_NAME}
    cap_add: 
      - IPC_LOCK
    ports:
      - '${APP_HTTP_PORT}:8200'
    env_file:
      - .env
    environment:
      - VAULT_LOCAL_CONFIG={}
    volumes:
      - 'vault-logs:/vault/logs'
      - 'vault-file:/vault/file'

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  vault-logs:
  vault-file:
