# image,docs: https://hub.docker.com/_/wordpress/

version: '3.8'

services:

  wordpress:
    image: wordpress:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    ports:
      - $APP_HTTP_PORT:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: $APP_NAME-db
      WORDPRESS_DB_USER: $APP_DB_MYSQL_USER
      WORDPRESS_DB_PASSWORD: $APP_DB_MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $APP_DB_MYSQL_NAME
    volumes:
      - wordpress:/var/www/html
      - ./src/php_exra.ini:/usr/local/etc/php/conf.d/php_exra.ini

  mysql:
    image: mariadb:$APP_DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_log_buffer_size=30M
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $APP_DB_MYSQL_NAME
      MYSQL_USER: $APP_DB_MYSQL_USER
      MYSQL_PASSWORD: $APP_DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $APP_DB_MYSQL_PASSWORD


volumes:
  wordpress:
  mysql_data:
    
networks:
  default:
    name: $APP_NETWORK
    external: true
