# image: https://hub.docker.com/r/gitea/gitea
# docs: https://docs.gitea.io/zh-cn/install-with-docker


version: '3.8'

services:
  gitea:
    image: gitea/gitea:$APP_VERSION
    container_name: $APP_NAME
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "$APP_HTTP_PORT:3000"
      - "$APP_SSH_PORT:22"
    depends_on:
       - mysql
 
  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  gitea: