# image: https://hub.docker.com/r/prestashop/prestashop
# docs: https://github.com/PrestaShop/docker

version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - prestashop:/var/www/html
    env_file: .env
    environment:
      - PS_DOMAIN=${APP_URL}
      - DB_SERVER=${APP_NAME}-db
      - DB_USER=${APP_DB_MYSQL_USER}
      - DB_PASSWD=${APP_DB_MYSQL_PASSWORD}
      - DB_PREFIX=ps_
      - ADMIN_MAIL=${APP_USER}
      - ADMIN_PASSWD=${APP_PASSWORD}
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  prestashop:
  mysql_data:
